### PR TITLE
Weather functional

### PR DESCRIPTION
**Pull request by VictorYarosh**

### CODE REVIEW

**Comment by VictorYarosh** [comment]
WIP

**Review by toserg — CHANGES_REQUESTED** [review]
Add to card block height: 525px.
Because when you refresh the page your blocks are jumping.

**Comment by toserg** [comment]
Please fix merge conflicts

**Comment by toserg** [comment]
Please update the LayoutStyled for fixing background issue:
`height: 100%;
    min-height: 100vh;`

**Comment by toserg** [comment]
Please fix loading, make it load in the center of the block

**Comment by VictorYarosh** [comment]
fix this , but what do you mean "Please fix merge conflicts"

**Review by toserg — APPROVED** [review]

**Review by toserg — APPROVED** [review]

**Pull request merged**
